# Generated by Django 4.2.8 on 2024-01-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_item'),
        ('delivery', '0003_alter_note_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='stock.item')),
                ('note', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='note_items', to='delivery.note')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='items',
            field=models.ManyToManyField(through='delivery.NoteItem',
                                         to='stock.item'),
        ),
    ]
