# Generated by Django 4.2.8 on 2024-01-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_noteitem_note_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteitem',
            options={'ordering': ['item__matchcode']},
        ),
    ]
