# Generated by Django 4.2.8 on 2024-01-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='matchcode',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
