# Generated by Django 4.2.8 on 2024-01-02 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_basketitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='basket_items', to='basket.basket'),
        ),
    ]
