# Generated by Django 4.2.8 on 2024-01-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_alter_basketitem_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ['item__matchcode']},
        ),
    ]
